# Generated by Django 5.1.7 on 2025-04-10 13:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='The image file.', storage=storages.backends.s3.S3Storage(), upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the service.', null=True, storage=storages.backends.s3.S3Storage(), upload_to='services/'),
        ),
    ]
